# Generated by Django 3.1.6 on 2021-06-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='S1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('Name', models.TextField(max_length=800, null=True)),
                ('Address', models.TextField(max_length=800, null=True)),
                ('Contact_Number', models.CharField(default='', max_length=12)),
                ('Email', models.TextField(max_length=800, null=True)),
                ('Contact_Person', models.TextField(max_length=800, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('kamote', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Laundrijess.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Laundrijess.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('price', models.FloatField()),
                ('Char', models.CharField(choices=[('Washing Machine', 'washing machine'), ('Dryer', 'dryer'), ('Washing Machine With Dryer', 'washing machine with dryer'), ('Extension', 'extension'), ('Automatic Washing Machine', 'automatic washing machine')], max_length=100)),
                ('description', models.TextField()),
                ('Patatas', models.ManyToManyField(null=True, to='Laundrijess.S1')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char', models.CharField(max_length=800, null=True)),
                ('For_Deliver', models.CharField(max_length=800, null=True)),
                ('For_Pickup', models.CharField(max_length=800, null=True)),
                ('Carrot', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laundrijess.s1')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char', models.CharField(max_length=800)),
                ('Carrot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Laundrijess.s1')),
            ],
        ),
        migrations.CreateModel(
            name='Bayad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char', models.CharField(max_length=800, null=True)),
                ('Payment', models.TextField(max_length=800, null=True)),
                ('Banana', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Laundrijess.delivery')),
            ],
        ),
    ]
